# Generated by Django 3.2.3 on 2021-06-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_site', '0004_alter_day_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='task_duration',
            field=models.IntegerField(null=True),
        ),
    ]
