# Generated by Django 3.2 on 2021-06-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_site', '0005_alter_event_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='weather_avg_temp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='weather_icon',
            field=models.TextField(null=True),
        ),
    ]
