# Generated by Django 3.2 on 2021-06-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_site', '0006_auto_20210614_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='weather_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
