# Generated by Django 3.2 on 2021-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_site', '0007_day_weather_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='task_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
