# Generated by Django 3.2.3 on 2021-05-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_done', models.CharField(max_length=200)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('task_time', models.TimeField(default=(2021, 5, 30, 18, 40, 58, 6, 150, 0))),
                ('current_feeling', models.CharField(choices=[(':D', 'Amazing'), (':)', 'Happy'), (':|', 'Okay'), (':/', 'Down'), (':(', 'Terrible')], default=':|', max_length=2)),
            ],
        ),
    ]
