# Generated by Django 3.2.3 on 2021-05-31 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True)),
                ('feeling', models.CharField(choices=[(':D', 'Amazing'), (':)', 'Happy'), (':|', 'Okay'), (':/', 'Down'), (':(', 'Terrible')], default=':|', max_length=2)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='current_feeling',
        ),
        migrations.AlterField(
            model_name='event',
            name='task_time',
            field=models.TimeField(default=(2021, 5, 31, 4, 5, 54, 0, 151, 0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='task_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_site.day'),
        ),
    ]
