# Generated by Django 3.2.3 on 2021-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='record_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='task_start_time',
            field=models.TimeField(),
        ),
    ]
